---
instrumentation:
  excludes:
    - tests/**/*.test.js
reporting:
  dir: ./.coverage/
  reports:
    - html
    - lcov
  watermarks:
    branches:
      - 80
      - 100
    functions:
      - 80
      - 100
    statements:
      - 80
      - 100
    lines:
      - 80
      - 100
