---
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
notifications:
  email: false
sudo: false
before_script:
  - npm prune
script:
  - npm test
branches:
  only:
    - master
